<?php
$standad = Mage::getSingleton('moip/standard');
$api = Mage::getSingleton('moip/api');
$api->setContaMoip($standad->getConfigData('conta_moip'));
$api->setAmbiente($standad->getConfigData('ambiente'));
$pgdireto = $api->hasPagamentoDireto();
$mostraboleto = 1;
$nivelestoque = $standad->getConfigData('estoqueboleto');
$idcount = 0;

	$_Produtos = Mage::getSingleton('checkout/cart')->getQuote()->getAllItems(); 
    foreach ($_Produtos as $value)
    {
        $item_ID = $value->getProductId();
        $_Product = Mage::getModel('catalog/product')->load($item_ID);
       	$model = Mage::getModel('catalog/product'); 
							$_product = $model->load($item_ID); 
							$stocklevel[$idcount] = (int)Mage::getModel('cataloginventory/stock_item')
                ->loadByProduct($_product)->getQty();
        $nomeprod[$idcount] = $model->getName();
       	$idcount = 	$idcount + 1;     
    } 
$idcount = 	$idcount - 1;  
$teste = 0;
while($teste <= $idcount )
{
	if ($stocklevel[$teste] <= $nivelestoque){
	
			$prodbaixostock = "O Produto <b>". $nomeprod[$teste] . "</b> está com o estoque baixo (<b>menos de  ". $stocklevel[$teste] ." unidades</b>) e não poderá ser pago com boleto. </br>
			A quantidade mínima de um produto em estoque para compra por boleto deverá ser de: <b>". $nivelestoque . " Produtos.</b>  ";
	$mostraboleto = 0;
}
$teste++;
 }


$nome =  Mage::getSingleton('customer/session')->getCustomer()->getName();
$telefone =  Mage::getSingleton('customer/session')->getCustomer()->getTelephone();
$cpf =  Mage::getSingleton('customer/session')->getCustomer()->getTaxvat();
$dn =  Mage::getSingleton('customer/session')->getCustomer()->getdob();
$dn = date("d/m/Y", strtotime($dn));
?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('o2ti_moip/css/formulario.css'); ?> "media="all">
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;margin-left:0px; ">
<div id="checkouto2ti">
<div id="payment_form_<?php echo $this->getMethodCode() ?>" >
<a href="https://site.moip.com.br/compra-protegida/" target="_blank" style="width:260px; float:left;margin-bottom: 15px;
text-align: center;"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/logomoip.png'); ?>" id="imageseguramoip" border="0"></a>

            <?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?>
<label id="meios">
<input onclick="cartao();" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="forma_pagamento" value="CartaoCredito" class="radio payment_method_handle validation-passed"  autocomplete="off">
<img  onclick=";" src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/abacartao.png'); ?>" id="imagemcartao" alt="Cartão de Crédito"   />
</label>
            <?php endif; ?>
            <?php if ($mostraboleto != "0"): ?>
    <?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>      
<label id="meios">
<input onclick="boleto();" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="forma_pagamento" value="BoletoBancario" class="radio payment_method_handle validation-passed" autocomplete="off">
<img onclick="" src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/ababoleto.png'); ?>"  id="imageboleto" alt="Boleto Bancário"   /></label>    
     <?php endif; ?>
           <?php endif; ?>
            <?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
<label id="meios"><input onclick="transf();" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="forma_pagamento" value="DebitoBancario" class="radio payment_method_handle validation-passed" autocomplete="off">
<img onclick=";" src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/abatransf.png'); ?>"  id="imagemtrans" alt="Transferência Bancária" /></label>
            <?php endif; ?>
            
             <?php if ($mostraboleto != "1"): ?>
    <?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>      
<label id="meios">
<input onclick="Estoque();" type="radio" id="forma_pagamento" name="payment[forma_pagamento]" title="forma_pagamento" value="" class="radio payment_method_handle validation-passed" autocomplete="off">
<img onclick="" src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/ababoleto.png'); ?>"  id="imageestoque" alt="Boleto Bancário"   /></label>    
     <?php endif; ?>
           <?php endif; ?>

</div>
<div id="checkout-payment-o2ti"></div>
<div id="moip_o2preencha">Por favor, primeiro preencha o endereço de cobrança!</div>
<?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?>
        <div id="moip_credito" >
        <div id="formcard" >
        <h3>Cartão de Crédito</h3>
<div id="dadosformcartao">
        <div id="bandeiramoipdiv">
		<div id="bandeiramoipa">
			<div id="bandeiramoipaa"><label id="band"><input id="bandeiramoip" type="radio" name="payment[credito_instituicao]" onclick="visa();"  value="Visa"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipvisa.png'); ?>" onclick=";"   id="Visa" alt="Visa" border="0"></label></div>
			<div id="bandeiramoipaa"><label id="band"><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]" onclick="mastercard();"  value="Mastercard"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipmaster.png'); ?>" onclick="" id="Mastercard" alt="Mastercard" border="0"></label></div>
			<div id="bandeiramoipaa"><label id="band"><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]" onclick="americanexpress();"  value="AmericanExpress"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipamerican.png'); ?>" onclick="" id="AmericanExpress" alt="AmericanExpress" border="0"></label></div>
			<div id="bandeiramoipaa"><label id="band"><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]" onclick="diners();"  value="Diners"> <img onclick="" src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moipdiners.png'); ?>" id="Diners" alt="Diners" border="0"></label></div>
			<div id="bandeiramoipaa"><label id="band"><input id="bandeiramoip" type="radio"  name="payment[credito_instituicao]" onclick="hipercard();"  value="Hipercard"><img onclick="" src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/moiphiper.png'); ?>" id="Hipercard" alt="Hipercard" border="0"></label></div>
		</div>
</div>
<div id="checkout-payment-bandeira"></div>
        <label id="dadoscartao" style="margin-top:15px;">Número:</label>
    <input type="text" name="payment[credito_numero]" id="credito_numero" class="required-entry validate-cc-number validate-cc-type"  onkeypress='return function(event)' autocomplete="off">
<br />
    <label id="dadoscartao">Validade:</label>
    <select name="payment[credito_expiracao_mes]" id="credito_expiracao_mes" class="required-entry" autocomplete="off">
      <option value="">Mês</option>
      <option value="01">01</option>
      <option value="02">02</option>
      <option value="03">03</option>
      <option value="04">04</option>
      <option value="05">05</option>
      <option value="06">06</option>
      <option value="07">07</option>
      <option value="08">08</option>
      <option value="09">09</option>
      <option value="10">10</option>
      <option value="11">11</option>
      <option value="12">12</option>
    </select>
    <select name="payment[credito_expiracao_ano]" id="credito_expiracao_ano" class="required-entry" autocomplete="off">
      <option value="">Ano</option>
      <option value="12">12</option>
      <option value="13">13</option>
      <option value="14">14</option>
      <option value="15">15</option>
      <option value="16">16</option>
      <option value="17">17</option>
      <option value="18">18</option>
      <option value="19">19</option>
      <option value="20">20</option>
      <option value="21">21</option>
      <option value="22">22</option>
      <option value="23">23</option>
      <option value="24">24</option>
      <option value="25">25</option>
    </select>
<br />
<span class="tooltip"  >
	<label id="dadoscartao">Código de segurança:</label>
    <input type="text" name="payment[credito_codigo_seguranca]" class="required-entry" style="width: 30px" id="credito_codigo_seguranca" autocomplete="off">
        <span class="custom help" style=" width:260px;"><em>Código de segurança:</em>Veja no verso do seu cartão.<img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/codigo-seguranca.png'); ?>" id="imageseguramoip" border="0"></span></span>

<br />
<?php


$data = $standad->getQuote()->getShippingAddress();
$data->getGrandTotal();

?>
            <?php if ($standad->getConfigData('parcelamento')): ?>
            <label id="dadoscartaoopc">Opções de pagamento:</label>
            <select name="payment[credito_parcelamento]" id="credito_parcelamento" class="required-entry" >
                                <?php
                                    $data = $standad->getQuote()->getShippingAddress();
                                    $parcelamento = $api->getParcelamento($data->getGrandTotal());

                                    foreach ($parcelamento as $k => $v): ?>
                                        <option value="<?php echo $k ?>"><?php echo $k . "x R$ " . $v['valor'] . " | Total: R$ " .$v['total']."" ?></option>
                                <?php endforeach; ?>
                                    </select>
            <?php endif; ?>
            <div id="addparcelas">
                                            <?php
                                            $standard = Mage::getSingleton('moip/standard');
                                                    $parcelamento = $standard->getInfoParcelamento();
                                            if ($parcelamento['juros1'] == 0)
                                            {
                                            echo "</br><div id=\"addparcelasdesc\"> Sem juros até ".$parcelamento['ate1']." parcelas</div>";
                                            if ($parcelamento['ate1'] < 13)
                                            {
                                            echo ", após juros de 1.99 ao mês.";
                                            }
                                            }
                                            if ($parcelamento['juros1'] >= "1.99")
                                            {
                                            echo "</br>Com juros de ".$parcelamento['juros1']." ao mês.";
                                            }
                                            ?>
                                         </div>
        </div>
        </div>
        <div id="alterar">
        <label>
        <input type="radio" border="0" onclick="alterar()" id="alterarin" autocomplete="off">
        Alterar dados do Titular do cartão
        </label>
        </div>
        <div id="manter">
        <label>
        <input type="radio" border="0" onclick="manter()" id="alterarin" autocomplete="off">
        Manter dados do Titular do cartão
        </label>
        </div>
        <div id="formcli">
        <h3>Dados do Titular</h3>
        <span class="tooltip" >
        <label id="dadoscliente">Nome no cartão:</label>
        <input type="text" name="payment[credito_portador_nome]" value="<?php echo $nome; ?>" class="required-entry" id="credito_portador_nome" autocomplete="off">
        <span class="custom help"><em>Nome do titular</em>deverá ser obrigatoriamente como descrito no cartão.</span></span>
        <label id="dadoscliente">CPF:</label>
        <input type="text" name="payment[credito_portador_cpf]" class="required-entry validar_cpf" placeholder="Ex. 111.111.111-11" id="credito_portador_cpf" value="<?php echo $cpf; ?>" autocomplete="off">
        <span class="tooltip" ><label id="dadoscliente">Telefone:</label>
        <input type="text" name="payment[credito_portador_telefone]" id="credito_portador_telefone" onkeypress="return txtBoxFormat(this, '(99)9999-9999', event);" maxlength="14" value="<?php echo $telefone; ?>" placeholder="Ex. (19)9999-9999" class="required-entry" autocomplete="off">
        <span class="custom help"><em>Telefone de contato</em>Muitas vezes é necessária a confirmação manual de seus dados por nossa equipe de crédito, por favor informe um telefone em que seja fácil te localizar.</span></span>
        <label id="dadoscliente">Data nascimento:</label>
        <input type="text" name="payment[credito_portador_nascimento]" id="credito_portador_nascimento" onkeypress="return txtBoxFormat(this, '99/99/9999', event);" maxlength="10" value="<?php echo $dn ?>" placeholder="Ex. 10/10/1985" class="required-entry" autocomplete="off">
        </div>
        </div>
    <?php endif; ?>
	<?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>
        <div id="moip_boleto" >
        <h3>Boleto Bancário</h3>
        <div id="pagboleto">
        <?php
        $standard = Mage::getSingleton('moip/standard');
        $parcelamento = $standard->getInfoParcelamento();
        if ($parcelamento['de2'] != 0)
        {
        echo "<div id=\"pagboletodesconto\">Com desconto de  ".$parcelamento['de2']."%</div><br>";
        }
        echo "Pagável em qualquer agência bancária ou casas lotéricas.";
        ?>
        </div>
        </div>
    <?php endif; ?>
	<?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
        <div id="moip_debito">
        <h3>Transferência Bancária</h3>
        <div id="pagdebito">
        Após finalizar o pedido você será redirecionado ao site do seu banco...
        </div>
        <div id="checkout-payment-o2ti-deb">
        Por favor, selecione o banco!
        </div>
        <div id="moip_debito_bandeiras">
        <label >
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]"  onclick="bb();"  value="BancoDoBrasil" autocomplete="off">
        <img  src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/bb.png'); ?>"  alt="Banco do Brasil" id="debbb" >
        </label>
        <label onclick="bradesco()">
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" onclick="bradesco();" value="Bradesco" autocomplete="off">
        <img  src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/bradesco.png'); ?>" id="debbradesco" alt="Bradesco" >
        </label>
        <label >
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" onclick="itau();"  value="Itau" autocomplete="off">
        <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/itau.png'); ?>" id="debitau" alt="Itaú"  >
        </label>
        <label >
        <input type="radio" id="debito_instituicao" name="payment[debito_instituicao]" onclick="banrisul();" value="Banrisul"  autocomplete="off">
        <img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/banrisul.png'); ?>" id="Banrisul" alt="Banrisul"  >
        </label>
        </div>
        </div>
<div id="checkout-payment-banco"></div>
    <?php endif; ?>
    <?php if ($mostraboleto != "1"): ?>    
    <div id="moip_estoque">
    <h3>Boleto Indisponível</h3>  
    <?php echo $prodbaixostock; ?>
    </div>
    <?php endif; ?>
<a href="https://site.moip.com.br/compra-protegida/" target="_blank"><img src="<?php echo $this->getSkinUrl('o2ti_moip/imagem/logomoipck.png'); ?>" id="imageseguramoip" border="0"></a>
</div>

</ul>
<script type="text/javascript">
jQuery(document).ready(function(){
	if(jQuery.browser.msie && jQuery.browser.version < 9){
		jQuery("#dadosformcartao input[type='radio']").css({
			display: "block",
			clear: "both"
		});
		jQuery("#dadosformcartao input[type='radio']").parent().css({
			textAlign: "center",
			display: "block"
		});
		jQuery("#moip_debito input[type='radio']").css({
			display: "block",
			clear: "both"
		});
		jQuery("#moip_debito input[type='radio']").parent().css({
			textAlign: "center",
			display: "block",
			float: "left"
		});
	}
});
</script>

<script type="text/javascript">
cartao = function(){
    document.getElementById('imagemcartao').style.opacity='1';
   	<?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?> document.getElementById('imagemtrans').style.opacity='0.4'; <?php endif; ?>
    <?php if ($mostraboleto != "0"): ?><?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>  document.getElementById('imageboleto').style.opacity='0.4';<?php endif; ?><?php endif; ?>
	if (!document.getElementById('shipping:firstname').value && !document.getElementById('billing:firstname').value)
		{
 		document.getElementById('moip_o2preencha').style.display = 'block';
 $MW_Onestepcheckout('#moip_o2preencha').hide();
				 $MW_Onestepcheckout("#moip_o2preencha").show("slow");
	   <?php if ($mostraboleto != "0"): ?><?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?> 	document.getElementById('moip_boleto').style.display = 'none'; <?php endif; ?><?php endif; ?>
			<?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?> document.getElementById('moip_debito').style.display = 'none'; <?php endif; ?>
		} else{
		 document.getElementById('moip_credito').style.display = 'block';
$MW_Onestepcheckout('#moip_credito').hide();
				 $MW_Onestepcheckout("#moip_credito").show("slow");
		 document.getElementById('moip_o2preencha').style.display = 'none';
		   <?php if ($mostraboleto != "0"): ?><?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?> document.getElementById('moip_boleto').style.display = 'none';  <?php endif; ?><?php endif; ?>
		   <?php if ($mostraboleto != "1"): ?>
		   document.getElementById('imageestoque').style.opacity='0.4';
		   document.getElementById('moip_estoque').style.display = 'none';
		   <?php endif; ?>
		  	<?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?> document.getElementById('moip_debito').style.display = 'none';  <?php endif; ?>
$MW_Onestepcheckout('#advice-required-entry_payment_o2ti').remove();
		}
	if (!document.getElementById('shipping:firstname').value) {
 		document.getElementById('credito_portador_nome').value = document.getElementById('billing:firstname').value + ' ' + document.getElementById('billing:lastname').value;
 		document.getElementById('credito_portador_telefone').value = document.getElementById('billing:telephone').value;
		document.getElementById('credito_portador_cpf').value = document.getElementById('billing:taxvat').value;
		document.getElementById('credito_portador_nascimento').value = document.getElementById('billing:day').value + '/' + document.getElementById('billing:month').value + '/' + document.getElementById('billing:year').value
} else {
 		document.getElementById('credito_portador_nome').value = document.getElementById('shipping:firstname').value + ' ' + document.getElementById('shipping:lastname').value;
 		document.getElementById('credito_portador_telefone').value = document.getElementById('shipping:telephone').value;
}
  };


boleto = function(){
                document.getElementById('moip_o2preencha').style.display='none';
                document.getElementById('moip_boleto').style.display='block';
				           $MW_Onestepcheckout('#moip_boleto').hide();
				           $MW_Onestepcheckout("#moip_boleto").show("slow");
				           document.getElementById('imageboleto').style.opacity='1';
				           <?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
				           document.getElementById('moip_debito').style.display='none'; 
                document.getElementById('imagemtrans').style.opacity='0.4';				           
				           <?php endif; ?>
                <?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?> 
                document.getElementById('moip_credito').style.display='none';
 														document.getElementById('moip_credito').style.display = 'none';                
                document.getElementById('imagemcartao').style.opacity='0.4'; 
                <?php endif; ?>
                $MW_Onestepcheckout('#advice-required-entry_payment_o2ti').remove();
				};
Estoque = function(){
                document.getElementById('moip_o2preencha').style.display='none';
                document.getElementById('moip_estoque').style.display='block';
				           $MW_Onestepcheckout('#moip_estoque').hide();
				           $MW_Onestepcheckout("#moip_estoque").show("slow");
				           document.getElementById('imageestoque').style.opacity='1';
				           <?php if (in_array("DebitoBancario", $standad->getFormasPagamento()) ): ?>
				           document.getElementById('moip_debito').style.display='none'; 
                document.getElementById('imagemtrans').style.opacity='0.4';				           
				           <?php endif; ?>
                <?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?> 
                document.getElementById('moip_credito').style.display='none';             
                document.getElementById('imagemcartao').style.opacity='0.4'; 
                <?php endif; ?>
                
				};
transf = function(){
				document.getElementById('moip_debito').style.display='block';
				$MW_Onestepcheckout('#moip_debito').hide();
				$MW_Onestepcheckout("#moip_debito").show("slow");
				document.getElementById('moip_debito_bandeiras').style.display='block';
				$MW_Onestepcheckout('#moip_debito_bandeiras').hide();
				$MW_Onestepcheckout("#moip_debito_bandeiras").show("slow");
				document.getElementById('moip_o2preencha').style.display='none';
				 <?php if ($mostraboleto != "0"): ?> <?php if (in_array("BoletoBancario", $standad->getFormasPagamento()) ): ?>
				 document.getElementById('imageboleto').style.opacity='0.4';
				 document.getElementById('moip_boleto').style.display='none';
				 <?php endif; ?><?php endif; ?>
				document.getElementById('moip_credito').style.display='none';
                 <?php if (in_array("CartaoCredito", $standad->getFormasPagamento()) ): ?> document.getElementById('imagemcartao').style.opacity='0.4';  <?php endif; ?>
                document.getElementById('imagemtrans').style.opacity='1';
     <?php if ($mostraboleto != "1"): ?>
		   document.getElementById('imageestoque').style.opacity='0.4';
		   document.getElementById('moip_estoque').style.display = 'none';
		   <?php endif; ?>           
$MW_Onestepcheckout('#advice-required-entry_payment_o2ti').remove();
};

bb = function(){
				document.getElementById('checkout-payment-o2ti-deb').style.display='none';
                document.getElementById('debbb').style.opacity='1';
                document.getElementById('debbradesco').style.opacity='0.4';
                document.getElementById('debitau').style.opacity='0.4';
                document.getElementById('Banrisul').style.opacity='0.4';
				document.getElementById('pagdebito').style.display='block';
				$MW_Onestepcheckout('#pagdebito').hide();
				$MW_Onestepcheckout("#pagdebito").show("slow");
document.getElementById('checkout-payment-banco').style.display='none';
			
};
bradesco = function(){
				document.getElementById('checkout-payment-o2ti-deb').style.display='none';
                document.getElementById('debbb').style.opacity='0.4';
                document.getElementById('debbradesco').style.opacity='1';
                document.getElementById('debitau').style.opacity='0.4';
                document.getElementById('Banrisul').style.opacity='0.4';
				document.getElementById('pagdebito').style.display='block';	
				$MW_Onestepcheckout('#pagdebito').hide();
				$MW_Onestepcheckout("#pagdebito").show("slow");
document.getElementById('checkout-payment-banco').style.display='none';
};
itau = function(){
				document.getElementById('checkout-payment-o2ti-deb').style.display='none';
                document.getElementById('debbb').style.opacity='0.4';
                document.getElementById('debbradesco').style.opacity='0.4';
                document.getElementById('debitau').style.opacity='1';
                document.getElementById('Banrisul').style.opacity='0.4';
				document.getElementById('pagdebito').style.display='block';	
				$MW_Onestepcheckout('#pagdebito').hide();
				$MW_Onestepcheckout("#pagdebito").show("slow");
document.getElementById('checkout-payment-banco').style.display='none';
};
banrisul = function(){
				document.getElementById('checkout-payment-o2ti-deb').style.display='none';
                document.getElementById('debbb').style.opacity='0.4';
                document.getElementById('debbradesco').style.opacity='0.4';
                document.getElementById('debitau').style.opacity='0.4';
                document.getElementById('Banrisul').style.opacity='1';
				document.getElementById('pagdebito').style.display='block';
				$MW_Onestepcheckout('#pagdebito').hide();
				$MW_Onestepcheckout("#pagdebito").show("slow");
document.getElementById('checkout-payment-banco').style.display='none';
};
visa = function(){
   document.getElementById('Visa').style.opacity='1';
   document.getElementById('Mastercard').style.opacity='0.4';
   document.getElementById('Diners').style.opacity='0.4';
   document.getElementById('AmericanExpress').style.opacity='0.4';
   document.getElementById('Hipercard').style.opacity='0.4';
document.getElementById('checkout-payment-bandeira').style.display='none';

};
mastercard = function(){
   document.getElementById('Visa').style.opacity='0.4';
   document.getElementById('Mastercard').style.opacity='1';
   document.getElementById('Diners').style.opacity='0.4';
   document.getElementById('AmericanExpress').style.opacity='0.4';
   document.getElementById('Hipercard').style.opacity='0.4';
document.getElementById('checkout-payment-bandeira').style.display='none';
};
americanexpress = function(){
   document.getElementById('Visa').style.opacity='0.4';
   document.getElementById('Mastercard').style.opacity='0.4';
   document.getElementById('Diners').style.opacity='0.4';
   document.getElementById('AmericanExpress').style.opacity='1';
   document.getElementById('Hipercard').style.opacity='0.4';
document.getElementById('checkout-payment-bandeira').style.display='none';
};

diners = function(){
   document.getElementById('Visa').style.opacity='0.4';
   document.getElementById('Mastercard').style.opacity='0.4';
   document.getElementById('Diners').style.opacity='1';
   document.getElementById('AmericanExpress').style.opacity='0.4';
   document.getElementById('Hipercard').style.opacity='0.4';
document.getElementById('checkout-payment-bandeira').style.display='none';
};

hipercard = function(){
   document.getElementById('Visa').style.opacity='0.4';
   document.getElementById('Mastercard').style.opacity='0.4';
   document.getElementById('Diners').style.opacity='0.4';
   document.getElementById('AmericanExpress').style.opacity='0.4';
   document.getElementById('Hipercard').style.opacity='1';
document.getElementById('checkout-payment-bandeira').style.display='none';
};
alterar = function(){
	document.getElementById('alterar').style.display='none';
	document.getElementById('formcli').style.display='block';
	document.getElementById('manter').style.display='block';
	$MW_Onestepcheckout('#formcli').hide();
	$MW_Onestepcheckout("#formcli").show("slow");
};
manter = function(){
	document.getElementById('manter').style.display='none';
	document.getElementById('formcli').style.display='none';
	document.getElementById('alterar').style.display='block';
	};
	</script>
